Add:
ArsenyIshtubaev/Shared-spending-service pull request #1
Opened 2022-03-12 08:12 UTC by ArsenyIshtubaev

-Session
-Member
-Expense

2022-03-12 09:23 UTC, Denis-26 requested changes

2022-03-12 09:23 UTC, Denis-26 commented on src/Expense.java
> +public class Expense {
сущность Expense - ок

2022-03-12 09:23 UTC, Denis-26 commented on src/Expense.java
> +    private Member payer;
payer понятно в целом, но я бы назвал просто from

2022-03-12 09:23 UTC, Denis-26 commented on src/Expense.java
> +    private ArrayList<Member> listMember;
не очень понял, что за список мемберов в трате

Думаю в трате нужно хранить информацию только о том, от кого и кому

2022-03-12 09:23 UTC, Denis-26 commented on src/Expense.java
> +public class Expense {
и нужно у каждой сущности иметь поле id

2022-03-12 09:23 UTC, Denis-26 commented on src/Expense.java
> +        this.payer = member;
создать объект можно, а как из него получить информацию из полей?

2022-03-12 09:23 UTC, Denis-26 commented on src/Member.java
> +public class Member {
id нужен и getters

2022-03-12 09:23 UTC, Denis-26 commented on src/Session.java
> +public class Session {
хорошо! по полям все ок, нужны getters как и везде)

2022-03-21 17:06 UTC, Denis-26 approved these changes

2022-03-22 14:01 UTC, merged

2022-03-22 14:02 UTC, ArsenyIshtubaev commented
-